# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_species_sample_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=250)),
                ('family', models.CharField(max_length=250)),
                ('genus', models.CharField(max_length=250)),
                ('sub_genus', models.CharField(max_length=250)),
                ('species', models.CharField(max_length=250)),
                ('taxa', models.CharField(max_length=250)),
                ('count', models.IntegerField()),
                ('percent_subsample', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_count', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
