# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160122_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=250, null=True)),
                ('installation', models.CharField(max_length=250, null=True)),
                ('drainage', models.CharField(max_length=250, null=True)),
                ('mountain_range', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
