# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sitemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('subsite', models.IntegerField(null=True)),
                ('microhabitat', models.CharField(max_length=250, null=True)),
                ('sample_hydro', models.CharField(max_length=250, null=True)),
                ('habitat_size', models.CharField(max_length=250, null=True)),
                ('pool_area', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('riff_area', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('canopy_upstream', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('canopy_left', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('canopy_downstream', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('average_canopy_cover', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('total_canopy_cover', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('bedrock', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('cobble', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('gravel', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('silt', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('travertine', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('sand', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('algae', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('macrophite', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('moss', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('detritus', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('temperature', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('disolved_oxygen', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('ph', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('conductivity', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('grazing_impact', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('collection_comments', models.TextField(null=True)),
                ('habitat_comments', models.TextField(null=True)),
                ('collector', models.CharField(max_length=250, null=True)),
                ('zone', models.CharField(max_length=250, null=True)),
                ('utm_easting', models.CharField(max_length=250, null=True)),
                ('utm_northing', models.CharField(max_length=250, null=True)),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.SiteModel')),
            ],
        ),
    ]
