# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160122_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsamplemodel',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.SampleModel'),
        ),
    ]
