# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subsamplemodel_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplemodel',
            name='algae',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='average_canopy_cover',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='bedrock',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='canopy_downstream',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='canopy_left',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='canopy_upstream',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='cobble',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='collection_comments',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='conductivity',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='detritus',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='disolved_oxygen',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='gravel',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='grazing_impact',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='habitat_comments',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='macrophite',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='moss',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='pool_area',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='riff_area',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='sand',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='silt',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='total_canopy_cover',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='travertine',
        ),
        migrations.RemoveField(
            model_name='subsamplemodel',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='subsamplemodel',
            name='count',
        ),
        migrations.RemoveField(
            model_name='subsamplemodel',
            name='percent_subsample',
        ),
    ]
