# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subsamplemodel_sample'),
    ]

    operations = [
    ]
