# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160202_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='sample_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
