# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_samplemodel_sample_name'),
        ('app', '0011_auto_20160202_0520'),
    ]

    operations = [
    ]
