# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
