# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_sitemodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsamplemodel',
            old_name='order',
            new_name='order_name',
        ),
    ]
