# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160203_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='latitude',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='samplemodel',
            name='longitude',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
