# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160224_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='season',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
